# Generated by Django 4.0.3 on 2022-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploaded/"),
        ),
    ]
