# Generated by Django 4.0.3 on 2022-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_image_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
