# Generated by Django 4.0.3 on 2022-04-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("gallery", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
