# Generated by Django 4.0.3 on 2022-04-04 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0007_alter_image_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="PresentationCard",
        ),
    ]
