# Generated by Django 4.0.3 on 2022-04-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_image_owner"),
        ("user", "0005_alter_user_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
